name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "**.lua"
      - .github/workflows/ci.yml
      - "README.md"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: todo-actions
        uses: dtinth/todo-actions@v0.2.0
